// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the processor/retrosampler component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("retrosampler")
	ScopeName = "github.com/rtodorov/retrosampler"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
