// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/rtodorov/retrosampler")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/rtodorov/retrosampler")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                       metric.Meter
	mu                                          sync.Mutex
	registrations                               []metric.Registration
	ProcessorRetrosamplerAppendErrors           metric.Int64ObservableCounter
	ProcessorRetrosamplerCorruptFragments       metric.Int64ObservableCounter
	ProcessorRetrosamplerDecidedEntries         metric.Int64ObservableGauge
	ProcessorRetrosamplerDuplicateKeeps         metric.Int64ObservableCounter
	ProcessorRetrosamplerEarlyExpiredSegments   metric.Int64ObservableCounter
	ProcessorRetrosamplerEffectiveWindowSeconds metric.Int64ObservableGauge
	ProcessorRetrosamplerExpiredBytes           metric.Int64ObservableCounter
	ProcessorRetrosamplerFlushErrors            metric.Int64ObservableCounter
	ProcessorRetrosamplerFlushRetries           metric.Int64ObservableCounter
	ProcessorRetrosamplerFlushedSpans           metric.Int64ObservableCounter
	ProcessorRetrosamplerKeptBus                metric.Int64ObservableCounter
	ProcessorRetrosamplerKeptLocal              metric.Int64ObservableCounter
	ProcessorRetrosamplerPendingFlushes         metric.Int64ObservableGauge
	ProcessorRetrosamplerPublishErrors          metric.Int64ObservableCounter
	ProcessorRetrosamplerPublishedKeeps         metric.Int64ObservableCounter
	ProcessorRetrosamplerShedFloorProtected     metric.Int64ObservableCounter
	ProcessorRetrosamplerShedNothingReclaimable metric.Int64ObservableCounter
	ProcessorRetrosamplerShedQueueFull          metric.Int64ObservableCounter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterProcessorRetrosamplerAppendErrorsCallback sets callback for observable ProcessorRetrosamplerAppendErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerAppendErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerAppendErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerAppendErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerCorruptFragmentsCallback sets callback for observable ProcessorRetrosamplerCorruptFragments metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerCorruptFragmentsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerCorruptFragments, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerCorruptFragments)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerDecidedEntriesCallback sets callback for observable ProcessorRetrosamplerDecidedEntries metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerDecidedEntriesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerDecidedEntries, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerDecidedEntries)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerDuplicateKeepsCallback sets callback for observable ProcessorRetrosamplerDuplicateKeeps metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerDuplicateKeepsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerDuplicateKeeps, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerDuplicateKeeps)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerEarlyExpiredSegmentsCallback sets callback for observable ProcessorRetrosamplerEarlyExpiredSegments metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerEarlyExpiredSegmentsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerEarlyExpiredSegments, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerEarlyExpiredSegments)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerEffectiveWindowSecondsCallback sets callback for observable ProcessorRetrosamplerEffectiveWindowSeconds metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerEffectiveWindowSecondsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerEffectiveWindowSeconds, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerEffectiveWindowSeconds)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerExpiredBytesCallback sets callback for observable ProcessorRetrosamplerExpiredBytes metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerExpiredBytesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerExpiredBytes, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerExpiredBytes)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerFlushErrorsCallback sets callback for observable ProcessorRetrosamplerFlushErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerFlushErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerFlushErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerFlushErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerFlushRetriesCallback sets callback for observable ProcessorRetrosamplerFlushRetries metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerFlushRetriesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerFlushRetries, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerFlushRetries)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerFlushedSpansCallback sets callback for observable ProcessorRetrosamplerFlushedSpans metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerFlushedSpansCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerFlushedSpans, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerFlushedSpans)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerKeptBusCallback sets callback for observable ProcessorRetrosamplerKeptBus metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerKeptBusCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerKeptBus, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerKeptBus)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerKeptLocalCallback sets callback for observable ProcessorRetrosamplerKeptLocal metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerKeptLocalCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerKeptLocal, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerKeptLocal)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPendingFlushesCallback sets callback for observable ProcessorRetrosamplerPendingFlushes metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPendingFlushesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPendingFlushes, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPendingFlushes)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPublishErrorsCallback sets callback for observable ProcessorRetrosamplerPublishErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPublishErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPublishErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPublishErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPublishedKeepsCallback sets callback for observable ProcessorRetrosamplerPublishedKeeps metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPublishedKeepsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPublishedKeeps, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPublishedKeeps)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerShedFloorProtectedCallback sets callback for observable ProcessorRetrosamplerShedFloorProtected metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerShedFloorProtectedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerShedFloorProtected, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerShedFloorProtected)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerShedNothingReclaimableCallback sets callback for observable ProcessorRetrosamplerShedNothingReclaimable metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerShedNothingReclaimableCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerShedNothingReclaimable, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerShedNothingReclaimable)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerShedQueueFullCallback sets callback for observable ProcessorRetrosamplerShedQueueFull metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerShedQueueFullCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerShedQueueFull, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerShedQueueFull)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorRetrosamplerAppendErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.append.errors",
		metric.WithDescription("Fragment appends that failed against the shard buffer. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerCorruptFragments, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.corrupt.fragments",
		metric.WithDescription("Fragment skip events - corrupt length or CRC mismatch at Collect, plus decode failures at flush. Events, not distinct fragments - a retried tick re-counts the same bad bytes on disk. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerDecidedEntries, err = builder.meter.Int64ObservableGauge(
		"otelcol.processor.retrosampler.decided.entries",
		metric.WithDescription("Live decided-set entries across shards. [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerDuplicateKeeps, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.duplicate.keeps",
		metric.WithDescription("Keep verdicts suppressed by the decided set (redelivery, multiple detectors, self-delivery). [Development]"),
		metric.WithUnit("{keeps}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerEarlyExpiredSegments, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.early_expired.segments",
		metric.WithDescription("Segments sacrificed early by the disk watermark rung. [Development]"),
		metric.WithUnit("{segments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerEffectiveWindowSeconds, err = builder.meter.Int64ObservableGauge(
		"otelcol.processor.retrosampler.effective_window.seconds",
		metric.WithDescription("Smallest effective retention window across shards. [Development]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerExpiredBytes, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.expired.bytes",
		metric.WithDescription("Bytes reclaimed by normal window expiry. [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerFlushErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.flush.errors",
		metric.WithDescription("Flush attempts the next consumer rejected. [Development]"),
		metric.WithUnit("{flushes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerFlushRetries, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.flush.retries",
		metric.WithDescription("Flush intents re-parked for retry after a downstream failure. [Development]"),
		metric.WithUnit("{flushes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerFlushedSpans, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.flushed.spans",
		metric.WithDescription("Kept spans emitted to the next consumer. [Development]"),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerKeptBus, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.kept.bus",
		metric.WithDescription("Traces decided kept by a bus broadcast. [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerKeptLocal, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.kept.local",
		metric.WithDescription("Traces decided kept by local detection. Includes keeps whose fragments all shed, so this can lead flushed spans under sustained shed. [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPendingFlushes, err = builder.meter.Int64ObservableGauge(
		"otelcol.processor.retrosampler.pending.flushes",
		metric.WithDescription("Flush intents parked awaiting retry. [Development]"),
		metric.WithUnit("{flushes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPublishErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.publish.errors",
		metric.WithDescription("Keep verdicts the bus refused. Each one re-parks the publish need-bit for retry. [Development]"),
		metric.WithUnit("{publishes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPublishedKeeps, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.published.keeps",
		metric.WithDescription("Keep verdicts published to the bus. [Development]"),
		metric.WithUnit("{keeps}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerShedFloorProtected, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.shed.floor_protected",
		metric.WithDescription("Fragments refused at the window floor while floor-protected data blocks early expiry. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerShedNothingReclaimable, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.shed.nothing_reclaimable",
		metric.WithDescription("Fragments refused at the window floor with no finalized segment left to sacrifice. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerShedQueueFull, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.shed.queue_full",
		metric.WithDescription("Ingest events refused because the shard queue had no free buffer. Counts refused keep verdicts as well as refused fragments. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
