// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/rtodorov/retrosampler")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/rtodorov/retrosampler")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                          metric.Meter
	mu                                             sync.Mutex
	registrations                                  []metric.Registration
	ProcessorRetrosamplerAppendErrors              metric.Int64ObservableCounter
	ProcessorRetrosamplerBaggageDivergenceMs       metric.Int64ObservableGauge
	ProcessorRetrosamplerBaggageMalformed          metric.Int64ObservableCounter
	ProcessorRetrosamplerBusDropped                metric.Int64ObservableCounter
	ProcessorRetrosamplerBusErrors                 metric.Int64ObservableCounter
	ProcessorRetrosamplerBusMalformed              metric.Int64ObservableCounter
	ProcessorRetrosamplerBusReconnects             metric.Int64ObservableCounter
	ProcessorRetrosamplerCorruptFragments          metric.Int64ObservableCounter
	ProcessorRetrosamplerDecidedEntries            metric.Int64ObservableGauge
	ProcessorRetrosamplerDetectedKeeps             metric.Int64ObservableCounter
	ProcessorRetrosamplerDuplicateKeeps            metric.Int64ObservableCounter
	ProcessorRetrosamplerEarlyExpiredSegments      metric.Int64ObservableCounter
	ProcessorRetrosamplerEffectiveWindowSeconds    metric.Int64ObservableGauge
	ProcessorRetrosamplerExpiredBytes              metric.Int64ObservableCounter
	ProcessorRetrosamplerFlushAgeRatio             metric.Float64Histogram
	ProcessorRetrosamplerFlushErrors               metric.Int64ObservableCounter
	ProcessorRetrosamplerFlushRetries              metric.Int64ObservableCounter
	ProcessorRetrosamplerFlushedSpans              metric.Int64ObservableCounter
	ProcessorRetrosamplerKeptBus                   metric.Int64ObservableCounter
	ProcessorRetrosamplerKeptLocal                 metric.Int64ObservableCounter
	ProcessorRetrosamplerPendingFlushes            metric.Int64ObservableGauge
	ProcessorRetrosamplerPendingPublishesAbandoned metric.Int64ObservableCounter
	ProcessorRetrosamplerPolicyEvalErrors          metric.Int64ObservableCounter
	ProcessorRetrosamplerPolicyMatches             metric.Int64ObservableCounter
	ProcessorRetrosamplerPublishErrors             metric.Int64ObservableCounter
	ProcessorRetrosamplerPublishedKeeps            metric.Int64ObservableCounter
	ProcessorRetrosamplerShedFloorProtected        metric.Int64ObservableCounter
	ProcessorRetrosamplerShedNothingReclaimable    metric.Int64ObservableCounter
	ProcessorRetrosamplerShedQueueFull             metric.Int64ObservableCounter
	ProcessorRetrosamplerSkewClamped               metric.Int64ObservableCounter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterProcessorRetrosamplerAppendErrorsCallback sets callback for observable ProcessorRetrosamplerAppendErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerAppendErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerAppendErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerAppendErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerBaggageDivergenceMsCallback sets callback for observable ProcessorRetrosamplerBaggageDivergenceMs metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerBaggageDivergenceMsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerBaggageDivergenceMs, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerBaggageDivergenceMs)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerBaggageMalformedCallback sets callback for observable ProcessorRetrosamplerBaggageMalformed metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerBaggageMalformedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerBaggageMalformed, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerBaggageMalformed)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerBusDroppedCallback sets callback for observable ProcessorRetrosamplerBusDropped metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerBusDroppedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerBusDropped, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerBusDropped)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerBusErrorsCallback sets callback for observable ProcessorRetrosamplerBusErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerBusErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerBusErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerBusErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerBusMalformedCallback sets callback for observable ProcessorRetrosamplerBusMalformed metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerBusMalformedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerBusMalformed, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerBusMalformed)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerBusReconnectsCallback sets callback for observable ProcessorRetrosamplerBusReconnects metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerBusReconnectsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerBusReconnects, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerBusReconnects)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerCorruptFragmentsCallback sets callback for observable ProcessorRetrosamplerCorruptFragments metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerCorruptFragmentsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerCorruptFragments, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerCorruptFragments)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerDecidedEntriesCallback sets callback for observable ProcessorRetrosamplerDecidedEntries metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerDecidedEntriesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerDecidedEntries, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerDecidedEntries)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerDetectedKeepsCallback sets callback for observable ProcessorRetrosamplerDetectedKeeps metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerDetectedKeepsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerDetectedKeeps, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerDetectedKeeps)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerDuplicateKeepsCallback sets callback for observable ProcessorRetrosamplerDuplicateKeeps metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerDuplicateKeepsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerDuplicateKeeps, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerDuplicateKeeps)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerEarlyExpiredSegmentsCallback sets callback for observable ProcessorRetrosamplerEarlyExpiredSegments metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerEarlyExpiredSegmentsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerEarlyExpiredSegments, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerEarlyExpiredSegments)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerEffectiveWindowSecondsCallback sets callback for observable ProcessorRetrosamplerEffectiveWindowSeconds metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerEffectiveWindowSecondsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerEffectiveWindowSeconds, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerEffectiveWindowSeconds)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerExpiredBytesCallback sets callback for observable ProcessorRetrosamplerExpiredBytes metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerExpiredBytesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerExpiredBytes, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerExpiredBytes)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerFlushErrorsCallback sets callback for observable ProcessorRetrosamplerFlushErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerFlushErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerFlushErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerFlushErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerFlushRetriesCallback sets callback for observable ProcessorRetrosamplerFlushRetries metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerFlushRetriesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerFlushRetries, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerFlushRetries)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerFlushedSpansCallback sets callback for observable ProcessorRetrosamplerFlushedSpans metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerFlushedSpansCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerFlushedSpans, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerFlushedSpans)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerKeptBusCallback sets callback for observable ProcessorRetrosamplerKeptBus metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerKeptBusCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerKeptBus, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerKeptBus)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerKeptLocalCallback sets callback for observable ProcessorRetrosamplerKeptLocal metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerKeptLocalCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerKeptLocal, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerKeptLocal)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPendingFlushesCallback sets callback for observable ProcessorRetrosamplerPendingFlushes metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPendingFlushesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPendingFlushes, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPendingFlushes)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPendingPublishesAbandonedCallback sets callback for observable ProcessorRetrosamplerPendingPublishesAbandoned metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPendingPublishesAbandonedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPendingPublishesAbandoned, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPendingPublishesAbandoned)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPolicyEvalErrorsCallback sets callback for observable ProcessorRetrosamplerPolicyEvalErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPolicyEvalErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPolicyEvalErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPolicyEvalErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPolicyMatchesCallback sets callback for observable ProcessorRetrosamplerPolicyMatches metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPolicyMatchesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPolicyMatches, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPolicyMatches)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPublishErrorsCallback sets callback for observable ProcessorRetrosamplerPublishErrors metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPublishErrorsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPublishErrors, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPublishErrors)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerPublishedKeepsCallback sets callback for observable ProcessorRetrosamplerPublishedKeeps metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerPublishedKeepsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerPublishedKeeps, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerPublishedKeeps)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerShedFloorProtectedCallback sets callback for observable ProcessorRetrosamplerShedFloorProtected metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerShedFloorProtectedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerShedFloorProtected, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerShedFloorProtected)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerShedNothingReclaimableCallback sets callback for observable ProcessorRetrosamplerShedNothingReclaimable metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerShedNothingReclaimableCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerShedNothingReclaimable, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerShedNothingReclaimable)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerShedQueueFullCallback sets callback for observable ProcessorRetrosamplerShedQueueFull metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerShedQueueFullCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerShedQueueFull, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerShedQueueFull)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterProcessorRetrosamplerSkewClampedCallback sets callback for observable ProcessorRetrosamplerSkewClamped metric.
func (builder *TelemetryBuilder) RegisterProcessorRetrosamplerSkewClampedCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.ProcessorRetrosamplerSkewClamped, obs: o})
		return nil
	}, builder.ProcessorRetrosamplerSkewClamped)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorRetrosamplerAppendErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.append.errors",
		metric.WithDescription("Fragment appends that failed against the shard buffer. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerBaggageDivergenceMs, err = builder.meter.Int64ObservableGauge(
		"otelcol.processor.retrosampler.baggage.divergence_ms",
		metric.WithDescription("Last observed (now - T0) - elapsed_ms divergence. Large values mean clock skew or a baggage propagation gap (ADR-003 rule 5). [Development]"),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerBaggageMalformed, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.baggage.malformed",
		metric.WithDescription("Baggage attributes present but unusable - wrong type, bad grammar, or overflow. Instrumentation misconfiguration, not a propagation gap. [Development]"),
		metric.WithUnit("{values}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerBusDropped, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.bus.dropped",
		metric.WithDescription("Keeps discarded client-side when this subscriber could not keep up - the documented operator trade of at_most_once core pub/sub (ADR-008 rule 6, ADR-011 rule 1). Always zero in durable mode, where a slow consumer resets and replays instead of dropping. [Development]"),
		metric.WithUnit("{keeps}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerBusErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.bus.errors",
		metric.WithDescription("Bus failures that reach no caller - asynchronous errors such as an auth or permissions refusal, and failed stream ensures. Sustained non-zero means this instance's keeps are not crossing the bus, however healthy the connection looks. [Development]"),
		metric.WithUnit("{errors}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerBusMalformed, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.bus.malformed",
		metric.WithDescription("Bus messages dropped for a wrong-length payload (the wire format is a 16-byte id plus an optional reason byte, ADR-011 rule 6). [Development]"),
		metric.WithUnit("{messages}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerBusReconnects, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.bus.reconnects",
		metric.WithDescription("Bus client reconnects. Durable mode replays the gap; at_most_once mode lost it silently. [Development]"),
		metric.WithUnit("{reconnects}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerCorruptFragments, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.corrupt.fragments",
		metric.WithDescription("Fragment skip events - corrupt length or CRC mismatch at Collect, plus decode failures at flush. Events, not distinct fragments - a retried tick re-counts the same bad bytes on disk. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerDecidedEntries, err = builder.meter.Int64ObservableGauge(
		"otelcol.processor.retrosampler.decided.entries",
		metric.WithDescription("Live decided-set entries across shards. [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerDetectedKeeps, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.detected.keeps",
		metric.WithDescription("Keep verdicts produced by local detection, by reason attribute - raw detection events, before decided-set dedup. [Development]"),
		metric.WithUnit("{keeps}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerDuplicateKeeps, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.duplicate.keeps",
		metric.WithDescription("Keep verdicts suppressed by the decided set (redelivery, multiple detectors, self-delivery). [Development]"),
		metric.WithUnit("{keeps}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerEarlyExpiredSegments, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.early_expired.segments",
		metric.WithDescription("Segments sacrificed early by the disk watermark rung. [Development]"),
		metric.WithUnit("{segments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerEffectiveWindowSeconds, err = builder.meter.Int64ObservableGauge(
		"otelcol.processor.retrosampler.effective_window.seconds",
		metric.WithDescription("Smallest effective retention window across shards. [Development]"),
		metric.WithUnit("s"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerExpiredBytes, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.expired.bytes",
		metric.WithDescription("Bytes reclaimed by normal window expiry. [Development]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerFlushAgeRatio, err = builder.meter.Float64Histogram(
		"otelcol.processor.retrosampler.flush.age.ratio",
		metric.WithDescription("Age of each flushed fragment batch's oldest span as a fraction of the configured W, recorded at flush. Mass near 1.0 means keeps barely beat expiry - the W-validation instrument (ADR-011 rule 9). [Development]"),
		metric.WithUnit("1"),
		metric.WithExplicitBucketBoundaries([]float64{0.1, 0.25, 0.5, 0.75, 0.9, 1, 1.25, 1.5}...),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerFlushErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.flush.errors",
		metric.WithDescription("Flush attempts the next consumer rejected. [Development]"),
		metric.WithUnit("{flushes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerFlushRetries, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.flush.retries",
		metric.WithDescription("Flush intents re-parked for retry after a downstream failure. [Development]"),
		metric.WithUnit("{flushes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerFlushedSpans, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.flushed.spans",
		metric.WithDescription("Kept spans emitted to the next consumer. [Development]"),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerKeptBus, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.kept.bus",
		metric.WithDescription("Traces decided kept by a bus broadcast. [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerKeptLocal, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.kept.local",
		metric.WithDescription("Traces decided kept by local detection. Includes keeps whose fragments all shed, so this can lead flushed spans under sustained shed. [Development]"),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPendingFlushes, err = builder.meter.Int64ObservableGauge(
		"otelcol.processor.retrosampler.pending.flushes",
		metric.WithDescription("Flush intents parked awaiting retry. [Development]"),
		metric.WithUnit("{flushes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPendingPublishesAbandoned, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.pending.publishes_abandoned",
		metric.WithDescription("Parked publish intents dropped past their decided deadline (~keep time + W). Past W no peer fragment survives, so the broadcast could cause nothing (ADR-011 r3). [Development]"),
		metric.WithUnit("{publishes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPolicyEvalErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.policy.eval_errors",
		metric.WithDescription("OTTL policy evaluations that errored, by policy attribute. Ignore-and-count semantics - the span did not match. [Development]"),
		metric.WithUnit("{evaluations}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPolicyMatches, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.policy.matches",
		metric.WithDescription("OTTL policy matches, by policy attribute. [Development]"),
		metric.WithUnit("{matches}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPublishErrors, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.publish.errors",
		metric.WithDescription("Keep verdicts the bus refused. Each one re-parks the publish need-bit for retry. [Development]"),
		metric.WithUnit("{publishes}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerPublishedKeeps, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.published.keeps",
		metric.WithDescription("Keep verdicts published to the bus. [Development]"),
		metric.WithUnit("{keeps}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerShedFloorProtected, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.shed.floor_protected",
		metric.WithDescription("Fragments refused at the window floor while floor-protected data blocks early expiry. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerShedNothingReclaimable, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.shed.nothing_reclaimable",
		metric.WithDescription("Fragments refused at the window floor with no finalized segment left to sacrifice. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerShedQueueFull, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.shed.queue_full",
		metric.WithDescription("Ingest events refused because the shard queue had no free buffer. Counts refused keep verdicts as well as refused fragments. [Development]"),
		metric.WithUnit("{fragments}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorRetrosamplerSkewClamped, err = builder.meter.Int64ObservableCounter(
		"otelcol.processor.retrosampler.skew.clamped",
		metric.WithDescription("Negative durations clamped to zero (ADR-008 rule 7) - span end before start, T0 ahead of the local clock, negative elapsed_ms. [Development]"),
		metric.WithUnit("{clamps}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
